source 'https://rubygems.org'

ruby '2.2.0'
gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass'
gem 'responders'
gem 'terminal-notifier'
gem 'rails_12factor', group: :production
gem 'omniauth'
gem 'omniauth-twitter'
gem 'd3_rails'
gem 'figaro'
gem 'bing_translator'
gem 'unicorn'
gem 'tf-idf-similarity'
gem 'angularjs-rails'
gem 'sanitize'
gem 'underscore-rails'
gem 'unicode_utils'
gem 'normalize-rails'
gem 'narray'
gem "browserify-rails"

group :development, :test do
  gem 'pry-rails'
  gem 'byebug'
  gem 'rspec-rails'
  gem 'web-console', '~> 2.0'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'spring'
  gem 'shoulda-matchers'
end
