# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dfef874babc8d4160d50fc6102a4f6c372db5fa59c5ebec00f10102682fe0d75f544949e2b47f333d9d16259a5d6d711fd90d9f051521faa066fa72ff2b2090

test:
  secret_key_base: c75434b01354f5e2442ef3bc1923b4f505a8f9b0e0b99efe6c0c0d191be3cd0674cf61750168de64a943f1c024b6964597780487d131409f377709df2da1abd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
